;;; package --- This init.el was originally generated by http://www.emacs-bootstrap.com/
;;; Commentary:
;;; This is my init file

;;; Code:

(add-to-list 'load-path (concat user-emacs-directory "elisp"))

(require 'base)
(require 'base-emacs)
(require 'base-theme)
(require 'base-extensions)
(require 'base-org)
(require 'base-functions)
;; Load configuration

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-safe-themes
   (quote
    ("2925ed246fb757da0e8784ecf03b9523bccd8b7996464e587b081037e0e98001" "aaeb61894d5d3c586d27cee61a3f54493c383733f8d900e05c6fbc8ef6d6bc93" "c53b6a09c7d997c3185cb1598de1d0ff15e1679f5445f9a6cb8b2bf4fc4e565a" "c8d19a09f9d2cb1d6aa6c57e1a86b2dab863cc77a3fc7225a4e60baba96726a1" "fa2b58bb98b62c3b8cf3b6f02f058ef7827a8e497125de0254f56e373abee088" "436b185b423b78eb5d110dc23f4b95d78a1f002d156f226b7e6e5b1f6493dda0" "bffa9739ce0752a37d9b1eee78fc00ba159748f50dc328af4be661484848e476" default)))
 '(org-duration-format (quote (("h") (special . 2))))
 '(package-selected-packages
   (quote
    (transient helm-core alert org-re-reveal calfw calfw-cal calfw-ical calfw-org dashboard deferred org-tracktable ox-hugo org-fancy-priorities org-present org-pomodoro org-clock-convenience org-plus-contrib org-gcal gnuplot request-deferred zoom wc-mode writegood-mode writeroom-mode spacemacs-theme winum toc-org shell-pop smartparens restart-emacs typo olivetti google-translate define-word fountain-mode evil-magit evil-tutor evil ess easy-hugo company helm-descbinds helm-projectile helm-swoop helm which-key general diminish spaceline poet-theme auto-compile use-package))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
